### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by aubergine10** [Celisuis/AdvancedDistrictOptions#1]
Still a newbie at C# - how to resolve these build errors?

![image](https://user-images.githubusercontent.com/1386719/61998717-16821c80-b0ac-11e9-86ca-b980f57da139.png)

**Comment by Celisuis** [comment]
You need to import the BuildingThemes.dll file from your Workshop folder.

Goto References -> Add Reference -> Browse and find the .dll file.

The same will have to be done with Modtools aswell.

It's because the project has to reference them for the compatibility patches to work :)
________________________________

**Comment by aubergine10** [comment]
That worked, thanks!
